export default {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  loginAdmin: "/login",
  users: "/dashboard/users",
  products: "/dashboard/products",
  new: "/dashboard/new",
  order: "/orders",
  cart: "/cart",
  authError: "/oauth/error",
  toc: "/toc",
  policy: "/policy",
};
